title: OSCP/eCPPTv3 notes
description: My OSCP and eCPPTv3 exam notes
theme: just-the-docs

url: https://krovs.github.io/testings/

aux_links:
  Repository: https://github.com/krovs/testings

color_scheme: purple

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"
