title: OSCP/eCPPTv3 notes
description: My OSCP and eCPPTv3 exam notes
theme: just-the-docs

url: https://krovs.github.io/testings/

aux_links:
  Repository: https://krovs.github.io/testings

color_scheme: purple

back_to_top: true
back_to_top_text: "Back to top"

